CC = gcc
CFLAGS = -I. -I/home/augustojv/devel-workspace/darknet/include -pedantic -Wall -O3
LDFLAGS = -L/home/augustojv/devel-workspace/darknet/ -ldarknet
DEPS =
OBJ = tds-main.o
MJSONDIR = utils/microjson-1.6

all: $(MJSONDIR) tds

$(MJSONDIR):
	$(MAKE) -C $@ $(MAKECMDGOALS)
        
%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

tds: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS) $(MJSONDIR)/mjson.o

.PHONY: all clean $(MJSONDIR)

clean:
	rm -f *.o tds
	$(MAKE) -C $(MJSONDIR) clean
 